### ISSUE TITLE
404 URL for the paint demo

### ISSUE THREAD

**Issue by JamesUK76** [domination/gvr-services-emulator#1]
Hi I was wondering where I could download this paint demo? The current link doesn't work.

Regards,
James

**Comment by UnoRich** [comment]
hi you can download from gvr-android-sdk . check this
https://github.com/domination/gvr-android-sdk

2016-07-23 4:42 GMT+09:00 JamesUK76 notifications@github.com:

**Comment by JamesUK76** [comment]
Ahh right, I did this and couldn't install it on my phone (non 6P phone), I assumed the link was some special modified APK at first but realised that didn't make sense since the old URL was still in one of these directories. So this can be installed on a non 6P phone somehow? (sorry I'm a total noob with this stuff)

**Comment by UnoRich** [comment]
for demo paint apk, check this official git of google vr developer site.
https://github.com/googlevr/gvr-unity-sdk  .

you have 6P phone or not has no difference installing paint demo. only
difference is if you have android N on 6P or some device(5X, 6) then you
have a system app which is google-vr-service. so it make you connect with
controller using bluetooth.
but if you don't have 6P and android N you can use domination's git
emulator. that make wifi connection for non android N.

2016-07-31 4:43 GMT+09:00 JamesUK76 notifications@github.com:

**Comment by JamesUK76** [comment]
Thankyou very much, will check it out now

**Comment by domination** [comment]
Thank you all,
This information is very useful, i will try remember adding links to other repos with to specific tree.

The right one for controllerpaint.apk is "GVR Android SDK 0.8.0"
https://github.com/googlevr/gvr-android-sdk/tree/c85649fc3c001a5e96e9c96a73d67e6385680574/ndk-beta/apks/
