### ISSUE TITLE
about libraries

### ISSUE THREAD

**Issue by gn00618777** [domination/gvr-services-emulator#2]
Hi  
I feel amazed this project, it bring me some direction about google vr service. And I have some confuses of libraries, you say "updated SDK to v0.8.1", does this sdk version same as "GVR Android SDK v0.8.1" of gvr-android-sdk project?

In addition, I have recognized you import some code follows:

i**mport com.google.vr.vrcore.controller.api.ControllerServiceConsts;
import com.google.vr.vrcore.controller.api.ControllerStates;
import com.google.vr.vrcore.controller.api.IControllerListener;
import com.google.vr.vrcore.controller.api.IControllerService;**

I can not find source code about above. Could you tell me kindly that all of above api are included in libraries such as *.aar?  

Thank you.

**Comment by domination** [comment]
Yes and yes.
All included *.aar are copied to /libraries
Last used version is v0.8.1
https://github.com/domination/gvr-services-emulator/tree/master/libraries
from
https://github.com/googlevr/gvr-android-sdk/tree/70c2ef4d7ee10d245e4016ba73b6c3a5cb218b18/libraries

**Comment by gn00618777** [comment]
It is unbelievable you tell me such helpful information to me rapidly. Thank you Mr. domination.
How did you find that you should import these in your service emulator?
**import com.google.vr.vrcore.controller.api.ControllerServiceConsts;
import com.google.vr.vrcore.controller.api.ControllerStates;
import com.google.vr.vrcore.controller.api.IControllerListener;
import com.google.vr.vrcore.controller.api.IControllerService;**

I decompile controllerclient.apk and google vr service.apk in google gvr-android-sdk project, nothing I can find. But, I can find source code about IControllerService  class and so on in your release 
samples-controllerclient.apk.

Could you give me some hint : D ??  

Thank you very much.

**Comment by domination** [comment]
Okey, but one hint:
Open gvr-android-sdk, and look at sample controllerclient
https://github.com/googlevr/gvr-android-sdk/blob/master/samples/sdk-controllerclient/src/main/java/com/google/vr/samples/controllerclient/ControllerClientActivity.java#L58

`ControllerManager`  ("Go to > Declaration" - I use Android Studio as IDE)
this class have to fields of type `IControllerService` and `IControllerListener`
and 2 methods start() and stop() - binding and unbinding to service.
Most interesting part is onServiceConnected

How? ech it took me 10 long nights to figure out how it work and deliver first version of this,
the most hard part was protocol.

Just dig, use right tools (eg. logcat), and dig harder, nothing else.

**Comment by gn00618777** [comment]
Mr. domination

1  Thanks your experience about that how to analyse the google vr service, I follow your step, import .aar   
   file of viersion sdk9.0 to AS, then the IDE will imply me we should import  those api, but it is still a   
   diffcult to realize all of flow of google vr service.

2 Because these are not a easy job, so I directly trace your service code, I understand you want to tell me  
   about  "onServiceConnected" and how it works.

3 Did you mean the most hard is protocol, is that "How to analyse bluetooth and service that can 
   translation to the phoneevent"? I recognized this format is external you defined?

4 In fact, I want a try that to analyse your service emulator to receive bluetooth protocol via 
   "readFromChannel" in "emulator/Controller.java", so that I can fill up the  bluetooth packet from controller of any device, these packets will be received by google vr service, further to update controller state in ControllerClient.apk.

   I think this way is not impossible,  because  your ControllerClient.apk using  such as controllerManager.start() or controller.update() or IControllerListener to update controller states same  as google sdk. Another example:

            **controllerListener.onControllerOrientationEvent(controllerOrientationEvent);** 

onControllerOrienationEvent() is declared at ControllerManager. So, I think, if I realize that contents of bletooth packet we fill up to let your service to  interpret, these packets should be interpreted by google service same. Ha, this is my ideas. If I wrong or offend you. Please let me know. Thank you.

**Comment by gn00618777** [comment]
Mr. domination. 

Could you give me a simple direction that how did you analysis this protocol? I added some log in controller phone, I found controller_emulator apk process byte array, and call socket to pass this arry, I have no idea to  know the compose of packet which are send to headset.

I expect your kindly reply, thank you.

**Comment by gn00618777** [comment]
Mr. Domination 

Please tell me what version of protobuffer compiler that you using?
I indeed need some of your suggestion. Thank you.

**Comment by gn00618777** [comment]
Mr. Domination
I really  appreciate your share this project at github, and I have realized protocol by tracing your code. And my company will stop  this schedule. Thank you.

**Comment by domination** [comment]
I'm glad that this code repository helped you.
